site_name: K3IM


docs_dir: _docs
site_dir: docs

# steals from Patrick Kidger

theme:
  name: "material"
  features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
  palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: amber
          toggle:
            icon: material/weather-night
            name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: amber
          toggle:
            icon: material/weather-sunny
            name: Switch to light mode

plugins:
  - mkdocstrings
  - search  # default search plugin; needs manually re-enabling when using any other plugins
  - autorefs  # Cross-links to headings
  - mknotebooks  # Jupyter notebooks

repo_url: https://github.com/anas-rz/k3im
repo_name: anas-rz/k3im
edit_uri: ""  # No edit button, as some of our pages are in /docs and some in /examples via symlink, so it's impossible for them all to be accurate

nav:
  - k3im: index.md
  - 1D Models: 1d_models.md
  - 2D Models: 2d_models.md
  - 3D Models: 3d_models.md
  - Space-Time Models: space_time_models.md
  - Examples 1D: examples/spin_up_the_simplest_1d.ipynb
  - Examples 2D: examples/spin_up_the_simplest.ipynb
  - Examples 3D/Space-Time: examples/spin_up_the_simplest_3d_video.ipynb
