from k3im.models.two_d.cait import CaiT2D
from k3im.models.two_d.convmixer import ConvMixer2D
from k3im.models.two_d.deepvit import DeepViT2D
from k3im.models.two_d.eanet import EANet2D
from k3im.models.two_d.fnet import FNet2D
from k3im.models.two_d.gmlp import gMLP2D
from k3im.models.two_d.simple_vit_with_register_tokens import SimpleViT_RT2D
from k3im.models.two_d.simple_vit import SimpleViT
from k3im.models.two_d.vit_with_patch_dropout import ViTPatchDrop2D
